name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11', 'platform=tvOS Simulator,OS=13.3,name=Apple TV 4K', 'platform=OS X']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Xcode Project
      run: swift package generate-xcodeproj
    - name: Build and Test
      run: xcodebuild clean test -destination "${destination}" -scheme 'BarcodeView-Package' ONLY_ACTIVE_ARCH=NO
      env: 
        destination: ${{ matrix.destination }}
    - name: Generate Code Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
