name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 11']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Xcode Project
      run: swift package generate-xcodeproj
    - name: Build and Test
      run: xcodebuild clean test -destination "${destination}" -scheme 'BarcodeView-Package' ONLY_ACTIVE_ARCH=NO
      env: 
        destination: ${{ matrix.destination }}
      
